### ISSUE TITLE
[Bug] Token Art not showing (v10)

### ISSUE THREAD

**Issue by Txus5012** [WBHarry/introduce-me#29]
In v10, when making the introduction with the HUD button the image isn't shown if it is set to the token art.
Also, nothing is shown if you use the sidebar button. The sound is played, though.

It seems to work well when using the editor buttons (Introduce and Private Preview).

**Comment by WBHarry** [comment]
I wasn't able to reproduce the first issue. The HUD button shows the image for me. I did correct a v10 data bug related to the sidebar however.

I think you might not be on the right version. Due to Foundry changing names on a variable in a later version of v10, the update button wouldn't show for the module. 😱 
But I released version **0.9.5.1**. Drop a message again if the first message still persists in that version

**Comment by Txus5012** [comment]
Tried the new update and works well. Thanks.
