### ISSUE TITLE
FeatureSuggestion [jrpg style of presentation]

### ISSUE THREAD

**Issue by 2old-4this** [WBHarry/introduce-me#3]
I would like the option for editable fixed position , with optional scale, and be a toggle when appear and disappear. 

This can be a great improvement from theater inserts and theater of the mind situations. 

Good work 👍

**Comment by WBHarry** [comment]
Nice to find people enjoying the module 😁 
So I understand the ideas:

- By editable fixed position I'm assuming you mean the position of the whole Introduction banner on the screen?
![image](https://user-images.githubusercontent.com/89362246/173207241-968d82e8-d692-4612-bef0-e84166aacb30.png)

- Are you thinking the scale of the whole introduction banner to make it really big/tiny as wanted?

- An option to have to manually close the presentation instead of having a duration until closing could be nice! 😄  
I added something like it for the Private Preview when changing colors, but it was intentionally rather slapdash. I could make a nicer thing than that on the right side somewhere 
![image](https://user-images.githubusercontent.com/89362246/173207393-e8506565-2c4b-4b7d-9ca8-36f91481a2d3.png)

**Comment by WBHarry** [comment]
I just released version 0.9.3 that adds Introduction Banner positioning and scaling.
It also includes the option to set Introduction Banner to not close automatically, which might also be nice for theater of the mind situations. 😄 
https://github.com/WBHarry/introduce-me/releases/tag/0.9.3

**Comment by 2old-4this** [comment]
Great work. Works like a charm. Inc more suggestions.
