### ISSUE TITLE
[FeatureSuggestion] configure directly in the token sheet

### ISSUE THREAD

**Issue by rinnocenti** [WBHarry/introduce-me#6]
it would be interesting that in the hud token there is only the option to display, and in the token sheet inside the appearance tab, the settings are made, so it is possible to define, without first putting it in the world, or even having a template for several npcs, for groups, and then edited individually on the tokens.

**Comment by WBHarry** [comment]
The reason I haven't added any settings into the sheets is because I want the module to be system agnostic. Actor sheets will be different in every system.

I do agree that it would be preferable to not have to place down a token to edit the settings of the actor though. 
I think a good way might be to add an option for settings in the menu you get when right-clicking an actor.
![image](https://user-images.githubusercontent.com/89362246/173207135-cbb9cc87-7937-48dd-8f71-f56e48494e3a.png)

**Comment by rinnocenti** [comment]
it can still be agnostic using the prototype token sheet, because every system has it.
you can even add a tab on the token prototype sheet like this:

![image](https://user-images.githubusercontent.com/3178127/173220370-06f5b78a-d0ee-4152-95e7-ae056ea7ce25.png)

Identity tab.. apparanece tab... introduce-me tab.
so the option would be in a more coherent place with the UX and keep it agnostic.

**Comment by WBHarry** [comment]
I just released version 0.9.3.1, moving the config away from the token HUD. 😄 
I settled on placing it as a header button in the Token Configuration rather than as a tab as it feels a better fit for something that doesn't directly alter the token's data.

https://github.com/WBHarry/introduce-me/releases/tag/0.9.3.1
